[package]
name = "envoy-wasm-jwt-filter"
version = "0.1.0"
authors = ["zifeng <zifeng.1024@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxy-wasm = "0.1.0"